[theme]
base = "dark"
primaryColor = "#1F4959"
backgroundColor = "#011425"
secondaryBackgroundColor = "#242424"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
