[theme]
base = "light"
primaryColor = "#6293CC"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#6293CC"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
